name: Kubernetes pipeline

trigger:
  - master
  - feature/*

pool: default

variables:
  - group: common

stages:
  # Continuous Integration Process
  - stage: CI
    jobs:
      - job: BuildAndPushDocker
        workspace:
          clean: all
        steps:
          - powershell: |
              if ( docker images $(registry_url)/weight-tracker -q )
              {
                docker rmi $(docker images  $(registry_url)/weight-tracker -q)
              }
            displayName: remove previous docker images

          - script: docker build -t $(registry_url)/weight-tracker:latest .
            displayName: Build an image

          - script: docker login -u $(registry_username) -p $(registry_password) $(registry_url)
            displayName: connect to azure container registry

          - script: docker push $(registry_url)/weight-tracker:latest
            condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
            displayName: Push the image to ther docker hub repository

  # Continuous Deployment Process for Staging Environment
  - stage: DeployToKubernetes
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: kubernetes
        displayName: Deploy to kubernetes
        environment: pool
        strategy:
          runOnce:
            deploy:
              steps:
                - powershell: |
                    if (kubectl get secret regcred){
                      kubectl delete secret regcred
                    }
                    kubectl create secret docker-registry regcred --docker-server=$(registry_url) --docker-username=$(registry_username) --docker-password=$(registry_password)
                  displayName: create secret regcred

                - script: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.2.0/deploy/static/provider/cloud/deploy.yaml
                  displayName: deploy ingress controller
  
                - powershell: |
                    Timeout /T 30;
                    kubectl apply -f ingress.yaml
                  displayName: apply ingress yaml

                - powershell: kubectl apply -f db.yaml
                  displayName: apply db yaml
                 
                - task: Delay@1
                  inputs:
                    delayForMinutes: 0.5   
              
                - powershell: |
                    kubectl get ingress | %{$_ -split "\n"} | Select-Object -index 1 | %{$_ -split '\s+'} | Select-Object -index 3 -outvariable IP;
                    Write-Host "##vso[task.setvariable variable=IP;]$IP"
                  displayName: get IP
                - powershell: |
                    kubectl get svc postgres-service | %{$_ -split "\n"} | Select-Object -index 1 | %{$_ -split '\s+'} | Select-Object -index 2  -outvariable pg_ip
                    Write-Host "##vso[task.setvariable variable=pg_ip;]$pg_ip"
                  displayName: get IP

                - powershell: |
                    kubectl delete secret env
                    kubectl create secret generic env `
                      --from-literal=PORT=8080 `
                      --from-literal=PGHOST=$(pg_ip) `
                      --from-literal=PGUSERNAME=$(pg_username) `
                      --from-literal=PGDATABASE=postgres `
                      --from-literal=PGPASSWORD=$(pg_password) `
                      --from-literal=PGPORT=5432 `
                      --from-literal=COOKIE_ENCRYPT_PWD=$(cookie_pwd)

                  displayName: create env

                - powershell: |
                    kubectl delete configmap oktadata 
                    kubectl create configmap oktadata `
                    --from-literal=HOST_URL="http://$(IP)" `
                    --from-literal=OKTA_ORG_URL=$(okta_org_url) `
                    --from-literal=OKTA_CLIENT_ID=$(okta_client_id) `
                    --from-literal=OKTA_CLIENT_SECRET=$(okta_client_secret)
                  displayName: create oktadata configmap

                - powershell: kubectl apply -f weightTrackerApp.yaml
                  displayName: apply weightTrackerApp yaml