name: Docker pipeline

trigger:
- master
- feature/*

pool: default

variables: 
- group: common

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    - powershell: |
        if ( docker images $(registry_url)/weight-tracker -q )
        {
          docker rmi $(docker images  $(registry_url)/weight-tracker -q)
        }
      displayName: remove previous docker images

    - script: docker build -t $(registry_url)/weight-tracker:latest .
      displayName: Build an image

    - script: docker login -u $(registry_username) -p $(registry_password) $(registry_url)
      displayName: connect to azure container registry
    
    - script: docker push $(registry_url)/weight-tracker:latest
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
      displayName: Push the image to ther docker hub repository

# Continuous Deployment Process for Staging Environment
- stage: DeployToStaging
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: staging
    displayName: Deploy to Staging
    pool: default
    strategy:
      runOnce:
        deploy:
          steps:
          - script: az aks get-credentials --resource-group $(cluster_resource_group) --name $(cluster_name)
            displayName: connect to cluster
          # - template: tools/kubernetesPipeline.yml
          #   parameters:
          #     pghost: $(stg_pghost)
          #     pg_username: $(pg_username)
          #     pg_password: $(pg_password)
          #     LB_ip: $(stg_LB_ip)
          #     okta_url: $(okta_url)
          #     okta_client_id: $(okta_client_id)
          #     okta_client_secret: $(okta_client_secret)
          #     ansible_username: $(ansible_username) 
          #     ansible_ssh_pass: $(ansible_ssh_pass)
          #     registry_username: $(registry_username)
          #     registry_password: $(registry_password)
          #     registry_url: $(registry_url)
          #     hosts:
          #     - 10.0.1.4            
          #     - 10.0.1.5            