apiVersion: apps/v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ3ZWlnaHR0cmFja2VyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJ3ZWlnaHR0cmFja2VyIiwicGFzc3dvcmQiOiJ3ZWlnaHR0cmFja2VyIiwiYXV0aCI6ImQyVnBaMmgwZEhKaFkydGxjanAzWldsbmFIUjBjbUZqYTJWeSJ9fX0=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: weighttrackeruriel.azurecr.io/weight-tracker
        name: webapp
      imagePullSecrets:
      - name: regcred