apiVersion: apps/v1
kind: Secret
metadata:
  name: registry-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: weighttrackeruriel.azurecr.io/weight-tracker
        name: webapp
      imagePullSecrets:
      - name: registrykey