apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: weighttrackeruriel.azurecr.io/weight-tracker
        name: webapp
      imagePullSecrets:
      - name: registrykey